# https://travis-ci.org/svrana/pipsqueak

language: python

# Use containers instead of full VMs for faster startup.
sudo: false

python:
    - 2.7

install:
    - travis_retry make install
    - travis_retry pip install codecov

script:
    - py.test

after_success:
    - codecov

