# https://travis-ci.org/svrana/pipsqueak

language: python

# Use containers instead of full VMs for faster startup.
sudo: false

python:
    - 2.7

install:
    - travis_retry make install
    - bash < (curl -s https://codecov.io/bash)

script:
    - py.test

