# https://travis-ci.org/svrana/pipsqueak

language: python

# Use containers instead of full VMs for faster startup.
sudo: false

python:
    - 2.7

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y pandoc

install:
    - travis_retry pip install -r dev-requirements.txt
    - travis_retry make install

script:
    - make coverage

after_success:
    - codecov

